### PR TITLE
Collection: Recently added item first

### PR DESCRIPTION
**Pull request by audreyt**
Currently we had to press "End" to scroll to bottom all the time

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
So, I both kinda like this overall, because I often expect the grain list to be "recent first", and find Collections not being so weird. But I also think this might be bothersome if I was trying to create an ordered list of grains in the collection, with the most important one first or something, and whatever less important thing I added later ending up on top.

So I guess I kinda feel like either we need a way for Collections to see a grain's last used time, or we need a way to just reorder grains in it.

This is not an approval or a disapproval of the change persay, just a thought.

**Comment by audreyt** [comment]
Because the "Add a grain..." is on top, I think adding it to the top makes more sense. Agreed that reordering is useful (perhaps through up/down buttons on the side), which can be added as a separate issue perhaps?

**Comment by ocdtrekkie** [comment]
Yeah, I guess my issue is that right now, the one Collection I use does have the most important grains at the top. And your change would reverse the order of grains in all existing Collections, am I right? So while it's impossible to know how many people have their Collections ordered somewhat intentionally, this change would be potentially upsetting (and unfixable by them, short of removing and re-adding all their grains).

**Comment by ocdtrekkie** [comment]
Looking at the collection that I refer to, actually, the order isn't all that great to begin with. :/ Still might be an issue for others, but I'm definitely sad about the ordering issue either way. Honestly, rather than individual up/down arrows and storing that, it might be better just to take from the Sandstorm grain list, and implement sorting by columns, and then have the collection remember which column, ascending/descending, it should sort the grains by. Then if you wanted you could number the grain titles and sort by name, or sort by added date in either direction or what-have-you.

**Comment by dwrensha** [comment]
I agree that this order makes more sense.

Thanks!

**Pull request merged**
